jobs:
  - name: set-self
    plan:
      - get: src
        trigger: true
      - set_pipeline: self
        file: src/ci/pipeline.yml

  - name: mirror-dockerhub-image
    plan:
      - get: docker-hub-image
        trigger: true
        params:
          format: oci

      - put: ecr-image
        params:
          image: docker-hub-image/image.tar

resources:
  - name: docker-hub-image
    type: registry-image
    source:
      repository: public.ecr.aws/lts/ubuntu
      tag: "22.04"

  - name: ecr-image
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: ubuntu
      tag: "22.04"
      aws_region: us-gov-west-1

  - name: src
    type: git
    source:
      uri: https://github.com/cloud-gov/ubuntu-mirror
      branch: main
      commit_verification_keys: ((cloud-gov-pgp-keys))

resource_types:
  - name: registry-image
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: registry-image-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: git
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: git-resource
      aws_region: us-gov-west-1
      tag: latest
